services:
  helloworld:
    image: "nginxdemos/hello:latest"
    volumes:
      - ./hellooverride:/usr/share/nginx/html
    deploy:
      replicas: 5
    networks:
      - lbnet
  loadbalancer:
    image: nginx:latest
    volumes:
      - ./lb-nginx-conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    networks:
      - lbnet
    depends_on:
      - helloworld
  sbapp:
    image: "annatsiunchik/devops-bootcamp:0.0.2"
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - DEVOPS=ANRI
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

networks:
  lbnet:
    driver: bridge