name: Publish Docker Image on Push

on:
  push:
    branches:
      - main
    paths:
      - task3/**

jobs:
  maven-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with maven
        run: |
          cd task3
          mvn clean package --file pom.xml  

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get CURRENT_POM_VERSION
        run: |
          cd task3
          CURRENT_POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "CURRENT_POM_VERSION=$CURRENT_POM_VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: task3
          push: 'true'
          tags: |
            annatsiunchik/devops-bootcamp:latest
            annatsiunchik/devops-bootcamp:${{ env.CURRENT_POM_VERSION }}-${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
            


#  docker-build-publish:
#    needs: maven-build
#    runs-on: ubuntu-latest
#
#    permissions:
#      id-token: write
#      contents: read
#
#    steps:
#      - name: Log in to Docker Hub
#        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
#        with:
#          username: ${{ secrets.DOCKER_USER }}
#          password: ${{ secrets.DOCKER_TOKEN }}
